services:
  test:
    platform: linux/amd64
    build:
      context: ./app  # Build context is the app directory
      dockerfile: Dockerfile.test  # Use Dockerfile.test
    depends_on:
      - redis # Ensure the Redis container is started first
    env_file:
      - .env  # Load environment variables from the .env file

  app:
    platform: linux/amd64
    build:
      context: ./app  # Build context is the app directory
      dockerfile: Dockerfile.app  # Use Dockerfile.app
      target: final
    ports:
      - "80:80"
    depends_on:
      - test # Ensure that the tests pass first
      - redis # Ensure the Redis container is started first
    env_file:
      - .env  # Load environment variables from the .env file

  redis:
    build:
      context: ./redis  # Build context is the redis directory
    ports:
      - "6379:6379"  # Map host port to container port
