source 'https://rubygems.org'
ruby '1.9.3'
gem 'sinatra'
gem 'rack'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-transactions'
gem 'redis'
gem 'fakeredis'
gem 'rack-test', :require => 'rack/test'