source 'https://rubygems.org'
#ruby '1.9.3'
ruby '2.0.0'
gem 'sinatra'
gem 'rack'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-transactions'
gem 'redis'
gem 'fakeredis'
gem 'thin'
gem 'rack-test', :require => 'rack/test'
