source 'https://rubygems.org'
gem 'rake'
gem 'sinatra'
gem 'rack'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dm-mysql-adapter'
gem 'dm-transactions'
gem 'dm-timestamps'
gem 'redis'
gem 'thin'
gem 'pony'
gem 'activerecord', '~> 4.2.7'
gem 'activerecord-mysql-adapter', '~> 0.0.1'
gem 'mysql2', '0.3.20'
gem 'public_suffix'

group :test do
  gem 'rack-test', :require => 'rack/test'
  gem 'minitest'
  gem 'fakeredis'
  gem 'capybara'
  gem 'poltergeist'
end
