# Session expiration in seconds
session_expires: 900

# The number of failed login attempts before the user's account is locked
max_login_attempts: 5
# The number of minutes after which an account will unlock automatically - leave blank to prevent accounts from auto-unlocking
release_account_lock_after: 10

# Indicate the identifiers that will be used to identify the user id and the reset_code in the password reset query string.
password_reset_user_identifier: 'n'
password_reset_user_key: 'c'

# Specify the length in minutes that a password reset request will remain active. The time should allow for the user to receive their email
# from the system with the link to their reset page
password_reset_timeout: 15

# Specify the password reset email parameters. The system will replace the following values if included in the body:
#   #{name?}           <= user.name
#   #{url?}            <= the URL to the user's reset page (You MUST include this one)
#   #{affiliation?}    <= the user.affiliation
#   #{group?}          <= the user.group.name
#   #{timeframe}       <= the timeout specified above
password_reset_email_from: 'brian.riley@ucop.edu'
password_reset_email_cc: ''
password_reset_email_bcc: ''
password_reset_email_subject: 'UCOP PID Service - Password reset'
password_reset_email_body: 
  'Hello #{name?},
	<br /><br />
	You specified that you have forgotten your password to the UCOP PID Service.
	<br /><br />
	To reset your password, please enter a new password on our secure <a href="#{url?}">password reset</a> page.<br />
	If you did not request a password reset, please ignore this message.
	<br /><br />
	For your security, this reset request will expire in #{timeframe} minutes.'

# The pages that the user should be sent to after the specified action completes successfully. E.g. go to the /link/index page after login
target_after_login: '/link/index'
target_after_logout: '/link/login'
target_after_password_reset: '/link/login'
target_after_forgotten_password: '/link/forgot'