source 'https://rubygems.org'

ruby '3.3.7'

gem 'sinatra'
gem 'puma'

gem 'activerecord', '7.2.2.1'
gem 'mysql2'
gem 'will_paginate'

gem 'redis'
gem 'mail'
gem 'nokogiri'

group :test do
  gem 'rack-test', require: 'rack/test'
  gem 'minitest'
  gem 'fakeredis'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'sqlite3'
end
